# NHL Trap Games

Definition: A trap game is about a good team underperforming when they're expected to win

In [1]:
import sys
import os
import polars as pl
from tqdm import tqdm

base_dir = '../'
sys.path.insert(1, base_dir)

import src.config as cfg
import src.utils as utils
import src.sportsipy_utils as sportsipy_utils

## Pull Schedule for Each NHL Team

Note: We are using *5 v 5* results to focus on a team's true underlying ability

In [2]:
# Warning: NHL Schedules not loading - https://github.com/davidjkrause/sportsipy/issues/14
# sportsipy_utils.pull_nhl_schedule('TOR', 2024)

In [57]:
# https://www.naturalstattrick.com/games.php?fromseason=20242025&thruseason=20242025&stype=2&sit=5v5&loc=B&team=All&rate=n
schedule_folder = f'{base_dir}data/natural_stat_trick'

df_games = []
for filename in tqdm(os.listdir(schedule_folder)):
    if 'games_' in filename:
        schedule_filepath = os.path.join(schedule_folder, filename)
        df_games_filepath = pl.scan_csv(schedule_filepath, null_values=["-"]).collect()
        if not df_games_filepath.is_empty():
            df_games += [df_games_filepath]
    
df_games = (pl.concat(df_games)
            .unique(subset=['Game', 'Team'], keep='first')
            .with_columns(
                pl.col('Game').str.split(" - ").list.get(0).str.strip_chars().str.strptime(pl.Datetime,'%Y-%m-%d').alias('Date')
            )
            .select(['Game', 'Team', 'Date', 'GF', 'GA', 'GF%', 'xGF', 'xGA', 'xGF%', 'SH%', 'SV%' ,'PDO'])
           )
utils.logger.info(f"Loaded {df_games.shape[0]/2} unique games from natural stattrick") 
df_games.head(5)

100%|██████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 92.41it/s]
2025-09-13 11:34:07,815 [1402038357.py:19] [INFO] Loaded 21528.0 unique games from natural stattrick

shape: (5, 12)
┌─────────────────────────────────┬──────────────────┬─────────────────────┬─────┬───┬───────┬───────┬───────┬───────┐
│ Game                            ┆ Team             ┆ Date                ┆ GF  ┆ … ┆ xGF%  ┆ SH%   ┆ SV%   ┆ PDO   │
│ ---                             ┆ ---              ┆ ---                 ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str                             ┆ str              ┆ datetime[μs]        ┆ i64 ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞═════════════════════════════════╪══════════════════╪═════════════════════╪═════╪═══╪═══════╪═══════╪═══════╪═══════╡
│  2021-01-24 - Avalanche 1, Duc… ┆ Anaheim Ducks    ┆ 2021-01-24 00:00:00 ┆ 2   ┆ … ┆ 40.42 ┆ 18.18 ┆ 96.15 ┆ 1.143 │
│  2016-12-29 - Rangers 6, Coyot… ┆ New York Rangers ┆ 2016-12-29 00:00:00 ┆ 1   ┆ … ┆ 57.29 ┆ 5.26  ┆ 86.67 ┆ 0.919 │
│  2010-12-31 - Senators 3, Blue… ┆ Ottawa Senators  ┆ 2010-12-31 00:00:00 ┆ 2   ┆ … ┆ 56.46 ┆ 7.14  ┆ 76.92 ┆ 0.841 │
│  2017-02-18 - Blues 2, Sabres … ┆ Buffalo Sabres   ┆ 2017-02-18 00:00:00 ┆ 2   ┆ … ┆ 28.98 ┆ 12.5  ┆ 100.0 ┆ 1.125 │
│  2019-03-11 - Senators 2, Flye… ┆ Ottawa Senators  ┆ 2019-03-11 00:00:00 ┆ 2   ┆ … ┆ 30.82 ┆ 10.0  ┆ 89.66 ┆ 0.997 │
└─────────────────────────────────┴──────────────────┴─────────────────────┴─────┴───┴───────┴───────┴───────┴───────┘

In [82]:
# Warning: for 1000 pairs of (game, team), there were no 5v5 goals scored extracted GF/GA numbers 
df_missing = df_games.filter(pl.col("GF%").is_null())
utils.logger.info(f"Found {df_missing.shape[0]} / {df_games.shape[0]} rows without any 5v5 goals")

2025-09-13 11:49:00,934 [3340401753.py:3] [INFO] Found 1050 / 43056 rows without any 5v5 goals

## Identify Trap Games

In [127]:
strength_col = "5v5 Points"
strong_threshold = 1.1
weak_threshold = 0.9

df_games_processed = (
    df_games.filter(pl.col("GF%").is_not_null())
      .unique(subset=['Game', 'Team'], keep='first')
      .sort("Game", descending=False)
      .with_columns([
        pl.when(pl.col("Date").dt.month() >= 7).then(pl.col("Date").dt.year() + 1)
            .otherwise(pl.col("Date").dt.year())
            .alias("Season"),
          pl.when(pl.col("GF%")>50).then(pl.lit(2))
              .when(pl.col("GF%")<50).then(pl.lit(0))
              .otherwise(pl.lit(1))
          .alias("5v5 Points")
      ])
    .with_columns([
        pl.col(strength_col).cum_sum().over(["Team", "Season"]).alias("Season to Date Total incl Current"),
        pl.col("GF%").cum_count().over(["Team", "Season"]).alias("# Games Season to Date incl Current")
    ])
    .with_columns(
        ((pl.col("Season to Date Total incl Current") - pl.col(strength_col))/
         (pl.col("# Games Season to Date incl Current") - 1)).alias(f"Season to Date Average {strength_col}")
    )
    .with_columns([
        ((pl.col(f"Season to Date Average {strength_col}") > strong_threshold) 
         & (pl.col("# Games Season to Date incl Current") > 20)).alias("is_strong"),
        ((pl.col(f"Season to Date Average {strength_col}") < weak_threshold) 
         & (pl.col("# Games Season to Date incl Current") > 20)).alias("is_weak")
    ])
)  
                     
display(df_games_processed.tail(5))
df_games_processed.mean()

shape: (5, 19)
┌────────────────────┬────────────────────┬──────────────┬─────┬───┬───────────────────┬───────────────────┬───────────┬─────────┐
│ Game               ┆ Team               ┆ Date         ┆ GF  ┆ … ┆ # Games Season to ┆ Season to Date    ┆ is_strong ┆ is_weak │
│ ---                ┆ ---                ┆ ---          ┆ --- ┆   ┆ Date incl Cu…     ┆ Average 5v5 Poi…  ┆ ---       ┆ ---     │
│ str                ┆ str                ┆ datetime[μs] ┆ i64 ┆   ┆ ---               ┆ ---               ┆ bool      ┆ bool    │
│                    ┆                    ┆              ┆     ┆   ┆ u32               ┆ f64               ┆           ┆         │
╞════════════════════╪════════════════════╪══════════════╪═════╪═══╪═══════════════════╪═══════════════════╪═══════════╪═════════╡
│ 2025-04-17 -       ┆ Columbus Blue      ┆ 2025-04-17   ┆ 6   ┆ … ┆ 78                ┆ 0.987013          ┆ false     ┆ false   │
│ Islanders 1, Blu…  ┆ Jackets            ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆           ┆         │
│ 2025-04-17 -       ┆ New York Rangers   ┆ 2025-04-17   ┆ 3   ┆ … ┆ 81                ┆ 1.0               ┆ false     ┆ false   │
│ Lightning 0, Ran…  ┆                    ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆           ┆         │
│ 2025-04-17 -       ┆ Tampa Bay          ┆ 2025-04-17   ┆ 0   ┆ … ┆ 81                ┆ 1.175             ┆ true      ┆ false   │
│ Lightning 0, Ran…  ┆ Lightning          ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆           ┆         │
│ 2025-04-17 - Red   ┆ Detroit Red Wings  ┆ 2025-04-17   ┆ 2   ┆ … ┆ 79                ┆ 0.987179          ┆ false     ┆ false   │
│ Wings 3, Map…      ┆                    ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆           ┆         │
│ 2025-04-17 - Red   ┆ Toronto Maple      ┆ 2025-04-17   ┆ 2   ┆ … ┆ 77                ┆ 1.144737          ┆ true      ┆ false   │
│ Wings 3, Map…      ┆ Leafs              ┆ 00:00:00     ┆     ┆   ┆                   ┆                   ┆           ┆         │
└────────────────────┴────────────────────┴──────────────┴─────┴───┴───────────────────┴───────────────────┴───────────┴─────────┘

shape: (1, 19)
┌──────┬──────┬─────────────────┬──────────┬───┬────────────────────────┬─────────────────────────────────┬───────────┬──────────┐
│ Game ┆ Team ┆ Date            ┆ GF       ┆ … ┆ # Games Season to Date ┆ Season to Date Average 5v5 Poi… ┆ is_strong ┆ is_weak  │
│ ---  ┆ ---  ┆ ---             ┆ ---      ┆   ┆ incl Cu…               ┆ ---                             ┆ ---       ┆ ---      │
│ str  ┆ str  ┆ datetime[μs]    ┆ f64      ┆   ┆ ---                    ┆ f64                             ┆ f64       ┆ f64      │
│      ┆      ┆                 ┆          ┆   ┆ f64                    ┆                                 ┆           ┆          │
╞══════╪══════╪═════════════════╪══════════╪═══╪════════════════════════╪═════════════════════════════════╪═══════════╪══════════╡
│ null ┆ null ┆ 2016-09-02      ┆ 1.927296 ┆ … ┆ 39.141266              ┆ NaN                             ┆ 0.200495  ┆ 0.200519 │
│      ┆      ┆ 12:12:30.749892 ┆          ┆   ┆                        ┆                                 ┆           ┆          │
└──────┴──────┴─────────────────┴──────────┴───┴────────────────────────┴─────────────────────────────────┴───────────┴──────────┘

In [128]:
# Double check season derivation is reasonable given lockout in the 2012-2013 season and pandemic in 2019-2020/2020-2021 seasons
df_games_processed.group_by("Season").agg(pl.col("Game").count()).sort("Game").head(5)

shape: (5, 2)
┌────────┬──────┐
│ Season ┆ Game │
│ ---    ┆ ---  │
│ i32    ┆ u32  │
╞════════╪══════╡
│ 2013   ┆ 1404 │
│ 2021   ┆ 1698 │
│ 2020   ┆ 2126 │
│ 2008   ┆ 2352 │
│ 2009   ┆ 2358 │
└────────┴──────┘

In [129]:
df_games_processed.filter(pl.col("Team")=="Toronto Maple Leafs").head(25)

shape: (25, 19)
┌──────────────────────────┬───────────────┬──────────────┬─────┬───┬───────────────────┬──────────────────┬───────────┬─────────┐
│ Game                     ┆ Team          ┆ Date         ┆ GF  ┆ … ┆ # Games Season to ┆ Season to Date   ┆ is_strong ┆ is_weak │
│ ---                      ┆ ---           ┆ ---          ┆ --- ┆   ┆ Date incl Cu…     ┆ Average 5v5 Poi… ┆ ---       ┆ ---     │
│ str                      ┆ str           ┆ datetime[μs] ┆ i64 ┆   ┆ ---               ┆ ---              ┆ bool      ┆ bool    │
│                          ┆               ┆              ┆     ┆   ┆ u32               ┆ f64              ┆           ┆         │
╞══════════════════════════╪═══════════════╪══════════════╪═════╪═══╪═══════════════════╪══════════════════╪═══════════╪═════════╡
│ 2007-10-03 - Senators 4, ┆ Toronto Maple ┆ 2007-10-03   ┆ 3   ┆ … ┆ 1                 ┆ NaN              ┆ false     ┆ false   │
│ Mapl…                    ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-10-04 - Maple Leafs ┆ Toronto Maple ┆ 2007-10-04   ┆ 1   ┆ … ┆ 2                 ┆ 1.0              ┆ false     ┆ false   │
│ 2, S…                    ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-10-06 - Canadiens   ┆ Toronto Maple ┆ 2007-10-06   ┆ 3   ┆ … ┆ 3                 ┆ 1.0              ┆ false     ┆ false   │
│ 3, Map…                  ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-10-09 - Hurricanes  ┆ Toronto Maple ┆ 2007-10-09   ┆ 0   ┆ … ┆ 4                 ┆ 1.333333         ┆ false     ┆ false   │
│ 7, Ma…                   ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-10-11 - Islanders   ┆ Toronto Maple ┆ 2007-10-11   ┆ 3   ┆ … ┆ 5                 ┆ 1.0              ┆ false     ┆ false   │
│ 1, Map…                  ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ …                        ┆ …             ┆ …            ┆ …   ┆ … ┆ …                 ┆ …                ┆ …         ┆ …       │
│ 2007-11-17 - Senators 0, ┆ Toronto Maple ┆ 2007-11-17   ┆ 1   ┆ … ┆ 21                ┆ 1.1              ┆ false     ┆ false   │
│ Mapl…                    ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-11-20 - Bruins 4,   ┆ Toronto Maple ┆ 2007-11-20   ┆ 1   ┆ … ┆ 22                ┆ 1.142857         ┆ true      ┆ false   │
│ Maple …                  ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-11-23 - Maple Leafs ┆ Toronto Maple ┆ 2007-11-23   ┆ 1   ┆ … ┆ 23                ┆ 1.090909         ┆ false     ┆ false   │
│ 1, S…                    ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-11-24 - Maple Leafs ┆ Toronto Maple ┆ 2007-11-24   ┆ 1   ┆ … ┆ 24                ┆ 1.043478         ┆ false     ┆ false   │
│ 1, C…                    ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
│ 2007-11-27 - Canadiens   ┆ Toronto Maple ┆ 2007-11-27   ┆ 2   ┆ … ┆ 25                ┆ 1.0              ┆ false     ┆ false   │
│ 4, Map…                  ┆ Leafs         ┆ 00:00:00     ┆     ┆   ┆                   ┆                  ┆           ┆         │
└──────────────────────────┴───────────────┴──────────────┴─────┴───┴───────────────────┴──────────────────┴───────────┴─────────┘

In [139]:
df_opponent = df_games_processed.select([
    pl.col("Game"),
    pl.col("Team").alias("Opponent"),
    pl.col(f"Season to Date Average {strength_col}").alias(f"Opponent Season to Date Average {strength_col}"),
    pl.col("is_strong").alias("Opponent is_strong"),
    pl.col("is_weak").alias("Opponent is_weak")
])

df_games_with_opponent = (
    df_games_processed.join(df_opponent, on="Game", how="left")
    .filter(pl.col("Team") != pl.col("Opponent"))
    .with_columns(
        (pl.col(f"Season to Date Average {strength_col}") - pl.col(f"Opponent Season to Date Average {strength_col}")).alias("Delta {strength_col}")
    )
)

assert df_games_with_opponent.shape[0] == df_games_processed.shape[0]

df_games_with_opponent.filter(pl.col(f"Delta {strength_col}").abs() >= 0.2)

shape: (20_438, 24)
┌─────────────────────┬────────────────────┬──────────────┬─────┬───┬────────────────────┬───────────┬──────────┬────────────────┐
│ Game                ┆ Team               ┆ Date         ┆ GF  ┆ … ┆ Opponent Season to ┆ Opponent  ┆ Opponent ┆ Delta          │
│ ---                 ┆ ---                ┆ ---          ┆ --- ┆   ┆ Date Averag…       ┆ is_strong ┆ is_weak  ┆ {strength_col} │
│ str                 ┆ str                ┆ datetime[μs] ┆ i64 ┆   ┆ ---                ┆ ---       ┆ ---      ┆ ---            │
│                     ┆                    ┆              ┆     ┆   ┆ f64                ┆ bool      ┆ bool     ┆ f64            │
╞═════════════════════╪════════════════════╪══════════════╪═════╪═══╪════════════════════╪═══════════╪══════════╪════════════════╡
│ 2007-09-30 - Kings  ┆ Los Angeles Kings  ┆ 2007-09-30   ┆ 1   ┆ … ┆ NaN                ┆ false     ┆ false    ┆ NaN            │
│ 1, Ducks 4          ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2007-09-30 - Kings  ┆ Anaheim Ducks      ┆ 2007-09-30   ┆ 2   ┆ … ┆ NaN                ┆ false     ┆ false    ┆ NaN            │
│ 1, Ducks 4          ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2007-10-03 -        ┆ Montreal Canadiens ┆ 2007-10-03   ┆ 0   ┆ … ┆ NaN                ┆ false     ┆ false    ┆ NaN            │
│ Canadiens 3, Hur…   ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2007-10-03 -        ┆ Carolina           ┆ 2007-10-03   ┆ 1   ┆ … ┆ NaN                ┆ false     ┆ false    ┆ NaN            │
│ Canadiens 3, Hur…   ┆ Hurricanes         ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2007-10-03 - Ducks  ┆ Detroit Red Wings  ┆ 2007-10-03   ┆ 0   ┆ … ┆ 2.0                ┆ false     ┆ false    ┆ NaN            │
│ 2, Red Win…         ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ …                   ┆ …                  ┆ …            ┆ …   ┆ … ┆ …                  ┆ …         ┆ …        ┆ …              │
│ 2025-04-17 -        ┆ Pittsburgh         ┆ 2025-04-17   ┆ 3   ┆ … ┆ 1.2125             ┆ true      ┆ false    ┆ -0.375         │
│ Capitals 2, Peng…   ┆ Penguins           ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2025-04-17 - Flames ┆ Los Angeles Kings  ┆ 2025-04-17   ┆ 0   ┆ … ┆ 0.923077           ┆ false     ┆ false    ┆ 0.414585       │
│ 5, Kings …          ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2025-04-17 - Flames ┆ Calgary Flames     ┆ 2025-04-17   ┆ 5   ┆ … ┆ 1.337662           ┆ true      ┆ false    ┆ -0.414585      │
│ 5, Kings …          ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2025-04-17 -        ┆ Ottawa Senators    ┆ 2025-04-17   ┆ 4   ┆ … ┆ 1.111111           ┆ true      ┆ false    ┆ -0.212377      │
│ Hurricanes 5, Se…   ┆                    ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
│ 2025-04-17 -        ┆ Carolina           ┆ 2025-04-17   ┆ 4   ┆ … ┆ 0.898734           ┆ false     ┆ true     ┆ 0.212377       │
│ Hurricanes 5, Se…   ┆ Hurricanes         ┆ 00:00:00     ┆     ┆   ┆                    ┆           ┆          ┆                │
└─────────────────────┴────────────────────┴──────────────┴─────┴───┴────────────────────┴───────────┴──────────┴────────────────┘